import { ArrowDownUp, ArrowRight, BookOpen, Check, MoreHorizontal, Plus, Search, Sparkles, Trash2 } from 'lucide-react'
import { useState } from 'react'
import type { Book } from '../types'
import { Cover, Empty, percentRead } from './UI'

export default function Library({ books, onImport, onRead, onUpdate, onRemove }: { books: Book[]; onImport: () => void; onRead: (book: Book) => void; onUpdate: (id: string, patch: Partial<Book>) => void; onRemove: (id: string) => void }) {
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('all')
  const [sort, setSort] = useState('recent')
  const [menu, setMenu] = useState<string | null>(null)
  const recent = [...books].filter(book => !book.completed).sort((a, b) => (b.openedAt ?? '').localeCompare(a.openedAt ?? ''))[0]
  const visible = books.filter(book => `${book.title} ${book.author}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'finished' ? book.completed : !book.completed && book.readPages.length > 0))).sort((a, b) => sort === 'title' ? a.title.localeCompare(b.title, 'ja') : sort === 'progress' ? percentRead(b) - percentRead(a) : (b.openedAt ?? b.addedAt).localeCompare(a.openedAt ?? a.addedAt))

  return <>
    <section className="page-heading library-heading"><div><div className="eyebrow"><span className="tiny-dot" /> 一日一歩 &nbsp; / &nbsp; ONE PAGE AT A TIME</div><h1>Make room for<br /><em>Japanese.</em></h1><p>A good story. A new word. A little progress.</p></div><div className="heading-note"><span lang="ja">読む</span><p>Small steps.<br />New worlds.</p></div></section>
    {recent && <section className="continue-card"><div className="continue-copy"><div className="eyebrow"><Sparkles size={13} /> {recent.openedAt ? 'PICK UP WHERE YOU LEFT OFF' : 'YOUR FIRST CHAPTER STARTS HERE'}</div><h2 lang="ja">{recent.title}</h2><p>{recent.openedAt ? `${recent.pages[recent.position].chapter} · Page ${recent.position + 1} of ${recent.pages.length}` : 'A small step into a new world. Your starter story is ready.'}</p><button className="primary" onClick={() => onRead(recent)}>{recent.openedAt ? 'Continue reading' : 'Start reading'}<ArrowRight size={17} /></button></div><div className="continue-art"><div className="art-orbit" /><span className="art-spark">✳</span><Cover book={recent} small /></div></section>}
    <section className="library-section"><div className="section-heading"><div className="section-title"><h2>Your library</h2><span className="count">{books.length}</span></div><button className="text-button" onClick={onImport}><Plus size={17} /> Add a book</button></div>
      <div className="library-toolbar"><div className="tabs" aria-label="Filter books">{[['all', 'All books'], ['reading', 'In progress'], ['finished', 'Finished']].map(([value, label]) => <button key={value} className={filter === value ? 'active' : ''} aria-pressed={filter === value} onClick={() => setFilter(value)}>{label}</button>)}</div><div className="library-controls"><label className="search-field"><Search size={16} /><input aria-label="Search books" placeholder="Find a book…" value={query} onChange={event => setQuery(event.target.value)} /></label><label className="sort-select"><ArrowDownUp size={16} /><select aria-label="Sort books" value={sort} onChange={event => setSort(event.target.value)}><option value="recent">Recent</option><option value="title">Title</option><option value="progress">Progress</option></select></label></div></div>
      {!visible.length && (query || filter !== 'all') ? <Empty icon={<Search />} title="Nothing on this shelf yet">Try another search or filter.</Empty> : <div className="book-grid">{visible.map(book => <article className="book-card" key={book.id}>
        <button className="cover-button" onClick={() => onRead(book)} aria-label={`Read ${book.title}`}><Cover book={book} /><span className="cover-open"><BookOpen size={19} /> Open book</span>{book.completed && <span className="finished-badge"><Check size={12} /> Finished</span>}</button>
        <div className="book-caption"><button className="book-name" lang="ja" onClick={() => onRead(book)}>{book.title}</button><div className="book-actions"><button className="icon-button small-icon" aria-label={`Options for ${book.title}`} aria-expanded={menu === book.id} onClick={() => setMenu(menu === book.id ? null : book.id)}><MoreHorizontal size={19} /></button>{menu === book.id && <><button className="menu-dismiss" aria-label="Dismiss book options" onClick={() => setMenu(null)} /><div className="book-menu"><button onClick={() => { onUpdate(book.id, { completed: !book.completed }); setMenu(null) }}><Check size={15} />{book.completed ? 'Mark unfinished' : 'Mark finished'}</button><button className="danger-text" onClick={() => { onRemove(book.id); setMenu(null) }}><Trash2 size={15} />Remove book</button></div></>}</div></div>
        <p className="book-meta">{book.format === 'sample' ? 'YOMU ORIGINAL' : book.format.toUpperCase()}<span>·</span>{book.pages.length} pages</p><div className="book-progress"><div style={{ width: `${percentRead(book)}%` }} /></div><p className="progress-label">{percentRead(book) ? `${percentRead(book)}% read` : 'A fresh beginning'}</p>
      </article>)}<button className="import-card" onClick={onImport}><span className="import-circle"><Plus size={23} strokeWidth={1.4} /></span><strong>A story of your own</strong><span>Drop a book here<br />or click to browse</span><small>PDF, EPUB & TXT</small></button></div>}
    </section>
  </>
}
